{{- range $route := .Values.k8s_httproutes -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ required "HTTPRoute name is required." $route.name }}
  {{- if $route.namespace }}
  namespace: {{ $route.namespace }}
  {{- end }}
  {{- if $route.annotations }}
  annotations:
  {{- toYaml $route.annotations | nindent 4 }}
  {{- end }}
  {{- if $route.clusterName }}
  clusterName: {{ $route.clusterName }}
  {{- end }}
  {{- if $route.deletionGracePeriodSeconds }}
  deletionGracePeriodSeconds: {{ $route.deletionGracePeriodSeconds }}
  {{- end }}
  {{- if $route.finalizers }}
  finalizers:
  {{- toYaml $route.finalizers | nindent 4 }}
  {{- end }}
  {{- if $route.generateName }}
  generateName: {{ $route.generateName }}
  {{- end }}
  {{- if $route.labels }}
  labels:
  {{- toYaml $route.labels | nindent 4 }}
  {{- end }}
spec:
  {{- if $route.parentRefs }}
  {{- range $ref := $route.parentRefs }}
  {{- if not $ref.name }}{{ fail "parentRef name field is required."}}{{ end }}
  {{- end }}
  parentRefs:
  {{- toYaml $route.parentRefs | nindent 4 }}
  {{- end }}
  {{- if $route.hostnames }}
  hostnames:
  {{- toYaml $route.hostnames | nindent 4 }}
  {{- end }}
  {{- if $route.rules }}
  rules:
  {{- toYaml $route.rules | nindent 4 }}
  {{- end }}
{{ end }}
