# This policy is configures workloads in the namespace to accept only encrypted requests with TLS. The policy applies to all services in the mesh in the namespace.
peer_authentications:
  - name: reflector-inbound-mtls-peer-authentication
    namespace: reflector
    mtls:
      mode: STRICT
