gateways:
  - name: vault-istio-ingress-gateway
    namespace: vault
    selector:
      istio: ingressgateway
    servers:
      - hosts:
          - vault.asrnet.com
        port:
          name: http
          number: 80
          protocol: HTTP
        tls:
          httpsRedirect: true
      - hosts:
          - vault.asrnet.com
        port:
          name: https
          number: 443
          protocol: HTTPS
        tls:
          mode: SIMPLE
          credentialName: vault.asrnet.com-cert

virtual_services:
  - name: vault-istio-ingress-virtual-service
    namespace: vault
    gateways:
      - vault-istio-ingress-gateway
    hosts:
      - vault.asrnet.com
      - vault.vault.svc.cluster.local
    http:
      - route:
          - destination:
              host: vault.vault.svc.cluster.local
              port:
                number: 8200

# This policy is configures workloads in the namespace to accept only encrypted requests with TLS. The policy applies to all services in the mesh in the namespace.
peer_authentications:
  - name: vault-inbound-mtls-peer-authentication
    namespace: vault
    mtls:
      mode: STRICT
