{{- range $appName := list "details" "productpage" "ratings" "reviews" }}
{{- if (dig $appName "serviceAccount" "create" $.Values.serviceAccount.create ($.Values | merge dict)) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bookinfo.serviceAccountName" (list $ $appName "") }}
  labels:
    {{- include "bookinfo.labels" (list $ $appName "") | nindent 4 }}
  {{- with (dig $appName "serviceAccount" "annotations" $.Values.serviceAccount.annotations ($.Values | merge dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ dig $appName "serviceAccount" "automount" $.Values.serviceAccount.automount ($.Values | merge dict) }}
{{- end }}
{{ end }}