k8s_gateways:
  - name: argocd-server-gateway
    namespace: argocd
    gatewayClassName: istio
    listeners:
      - name: argocd-server
        port: 80
        protocol: HTTP
        hostname: argocd.asrnet.com
        allowedRoutes:
          namespaces:
            from: Same
k8s_httproutes:
  - name: argocd-server-httproute
    namespace: argocd
    parentRefs:
      - name: argocd-server-gateway
    hostnames:
      - argocd.asrnet.com
    rules:
      - backendRefs:
          - name: argocd-server
            port: 80
