---
cr:
  create: true
  namespace: kiali
  spec:
    auth:
      strategy: anonymous
    istio_namespace: istio-system
    external_services:
      prometheus:
        url: http://prometheus-server.prometheus.svc.cluster.local
      istio:
        egress_gateway_namespace: istio-egress
        ingress_gateway_namespace: istio-ingress
      grafana:
        enabled: true
        internal_url: http://grafana.grafana.svc.cluster.local
        external_url: http://grafana.asrnet.com
        auth:
          type: basic
    deployment:
      pod_labels:
        sidecar.istio.io/inject: "true"
      pod_annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
